### ISSUE TITLE
full csv created but one line JSON result

### ISSUE THREAD

**Issue by mlohry** [ROCm/rocprofiler#104]
System: ubuntu 22.04, Radeon VII, rocm-5.4.3.

Following the rocprof user guide example, I am able to successfully run the linked MatrixMultiplication.cpp with `rocprof --hsa-trace --hip-trace matrixmul` and it produces the expected json and csv output described in the docs.

Running the same thing on a more complex production code (built on top of RAJA's HIP interface), I no longer see the `results.json' is generating` message. `results.json` is created, but contains only a single line:

```
,{"args":{"name":"COPY"},"ph":"M","pid":1,"name":"process_name","sort_index":0}
```

The `results.stats.csv` however looks correct -- several dozen hip kernels are traced, showing number of calls, percentage time, etc.. Any idea what I might be doing wrong?

**Comment by ppanchad-amd** [comment]
@mlohry Apologies for the lack of response. Can you please check if your issue still exists with the latest ROCm 6.2? If resolved, please close the ticket. Thanks!

**Comment by darren-amd** [comment]
Hi @mlohry,

I went ahead and tested a few samples on rocprof without being able to reproduce your error on the latest ROCm version (6.2). I suspect that the error may be with the specific code you are running. 

Could you please see if the issue persists when you update to the latest version of ROCm and if it does provide me with the code sample so that I may further investigate? Thanks!

**Comment by darren-amd** [comment]
Hi @mlohry,

I am going to close this ticket due to inactivity. Please open another ticket if the issue persists, thanks!
