### ISSUE TITLE
rocprofv2 session name is not recognized when used with mpiexec

### ISSUE THREAD

**Issue by jdgh000** [ROCm/rocprofiler#123]
ROCm5.6, ubuntu 22.04.
1. I tried issuing following command and syntax looks correct but it complains about session name:
2. Secondly, it shows example using amdsys not rocsys, which I am confused which one to use. amdsys is not available on my system.

**rocsys --session session1  launch mpiexec -n 2  rocprofv2 --hip-api ./p61.out amdsys: start must be preceeded by --session <name>**
        amdsys --session <name> start
amdsys: stop must be preceeded by --session <name>
        amdsys --session <name> stop
amdsys: launch must be preceeded by --session <name>
        **e.g. amdsys --session <SESSION_NAME> launch <MPI_COMMAND> <MPI_ARGUMENTS> rocprofv2 <ROCPROFV2_OPTIONS> <APP_EXEC>**
where all mpiexec options must come before amdsys
: 0

**Comment by tcgu-amd** [comment]
Thanks for reporting the error!

There is a bug in the source code for the `rocsys` tool that came with version 5.6. The simple solution is to install `rocsys` from rocprofiler builds for ROCm versions >= 5.7. They should be compatible with rocprofilers builds for ROCm 5.6 as well. 

FYI, the root cause was that `amdsys` was just named to `rocsys` in the 5.6 build, butthe naming in the source code was not updated correctly. This resulted in [this line](https://github.com/ROCm/rocprofiler/blob/rocm-5.6.x/src/tools/amdsys/amdsys.cpp#L115) not being correctly executed, as well as the outdated error message saying `amdsys`.

The naming was updated to the correct version in [this commit ](https://github.com/ROCm/rocprofiler-internal/commit/3368b7483f7bf3db1d89d898d7c31cce6e5bb8a4)
