### ISSUE TITLE
[Feature]: controlling the profiling scope

### ISSUE THREAD

**Issue by maartenarnst** [ROCm/rocprofiler#136]
### Suggestion Description

The documentation for `rocprofiler-v1` indicates that the profiling scope can be controlled by "dispatch range" and "kernel name". Here, the "dispatch range" is an index or a range of indices of dispatch ranges. However, when using `roctx` markup, the ranges are labelled with strings by their names, and not with numbers by indices. Indeed, `roctxRangeStart` takes the name as input, and it returns the index, but this index is typically an internal number in the code, not accessible to the user.

Thus, a useful feature may be to provide the ability to control the profiling scope by passing the name of the roctx range.

The feature would be similar to `--nvtx-include` and `--nvtx-exclude` that can be passed to `ncu` on Cuda.

A related question is how the profiling scope should/can be controlled in `rocprofiler-v2`.

**Comment by sohaibnd** [comment]
Hi @maartenarnst, sorry for the delay. I think there might be confusion between the different features so let me clarify:

Firstly, there are two modes for profiling in rocprof: **application tracing** which lets you trace different functions (like HIP APIs, HSA APIs, kernel dispatches, memory copy, and user defined markers) throughout the execution of the program depending on the options you specify, and **kernel profiling** which lets you collect HW counters and derived metrics for the kernels being executed on the GPU.

Now, controlling the profiling scope with dispatch range and kernel name is only possible in kernel profiling mode (by specifying the range and kernel fields in your input file, see [doc](https://rocm.docs.amd.com/projects/rocprofiler/en/latest/how-to/using-rocprof.html#input-file)), not in application tracing mode. 

On the other hand, the ROCTx Trace feature (**in application tracing mode**) you mentioned is meant to let you specify custom markers and ranges in your code that you want to include in your trace. Note that these markers and ranges are **trace points**, they do not control profiling scope (i.e. they are not start and stop points for collecting other counters/metrics).

So these features are not related. Please let me know if that answers your question!



**Side Note**: rocprofv1 is no longer under development and there is a new [rocprofv3](https://rocm.docs.amd.com/projects/rocprofiler-sdk/en/latest/index.html) released in ROCm 6.2 as a beta, which is built on top of the new [rocprofiler-sdk](https://github.com/ROCm/rocprofiler-sdk). I strongly suggest using rocprofv3 since it is very close to having feature parity, has a lower overhead than v1 and v2, and is significantly better tested. You can use the ROCTx Trace feature in rocprofv3 with the --marker-trace option (see [doc](https://rocm.docs.amd.com/projects/rocprofiler-sdk/en/docs-6.2.1/how-to/using-rocprofv3.html#marker-trace)), instead of the --roctx-trace used in rocprof v1 and v2.

**Comment by sohaibnd** [comment]
@maartenarnst I'm going to close this issue due to inactivity. If you have any other questions, feel free to re-open this issue.

**Comment by maartenarnst** [comment]
Dear @sohaibnd. Thanks. Sorry for the inactivity and for not having responded yet to the previous response. My impression is that being able to do “kernel profiling” in a region identified by roctx markers would be a useful feature. And the previous response seems to confirm that such a feature is not currently provided. On my side, I would suggest to keep this issue open, so that such a feature can be considered for future extensions to rocprofv3.

**Comment by jrmadsen** [comment]
@maartenarnst Just so you are aware, in the new ROCTx (rocprofiler-sdk-roctx), there are new functions `roctxProfilerPause` and `roctxProfilerResume` which allow you to control the scope of the profiling data programmatically.

**Comment by maartenarnst** [comment]
Hi @jrmadsen. Thanks for the suggestion. Indeed, using `roctxProfilerPause` and `roctxProfilerResume` is a way forward.

Just a few more details on the use case we see. Our use case is to do "kernel profiling" in a `Kokkos` code, for which we have both a Cuda and a HIP backend. We mark the region that we're interested in as a `Kokkos::Profiling::ProfilingSection`. This maps to `nvtx` markers in the Cuda backend and to `roctx` markers in the HIP backend. For the Cuda backend, we can then use `ncu` with the `--nvtx-include` argument to limit the profiling to the intended region. However, for the HIP backend, we cannot currently do this, hence, this issue.

I think that having a feature to do “kernel profiling” in a region identified by `roctx` markers would be useful because it would be more general than `roctxProfilerPause` and `roctxProfilerResume`. In addition, in the context of implementing performance portable codes, providing in `rocprofiler` such a feature similar to `ncu` allows backend specificities in the performance portable code to be avoided.

Also tagging @romintomasetti.

**Comment by jrmadsen** [comment]
@maartenarnst we will think through it. While it sounds straightforward on the surface (matching includes call roctxProfilerResume, matching excludes call roctxProfilerPause), the behavior intermixed with raw pause/resume calls needs to be defined (i.e. raw profiler pause in code followed by an “included” ROCTx region — do we enable? Ignore?). We also need to consider an included region running on one thread and an excluded region running on another thread. 

Using pause/resume can/will reduce the profiler overhead but solving the aforementioned issues suggests that rocprofv3 should just collect all the data and filter the excluded data from the output. And if that’s all the options are actually doing, it seems to me that a Python post-processing analysis suite could just as easily provide this capability (which is something we’d prefer to move towards)
