### ISSUE TITLE
Fbar, the kernel's barriers limitation

### ISSUE THREAD

**Issue by etiennemlb** [ROCm/rocprofiler#99]
Hi,
I would like to get more details about the `fbar` information reported by rocprof.

What does it mean. 
How can it be interpreted.

Is it related to : 
`Max fbarriers/Workgrp:   32 `
Which is given by rocminfo.

Thanks

**Comment by ppanchad-amd** [comment]
@etiennemlb Apologies for the lack of response. Do you still need assistance with this ticket? If not, please close the ticket. Thanks!

**Comment by etiennemlb** [comment]
Yes I would like more/extensive documentation on the counter the AMD GPUs provide. Do you have a document I could rely on ?

Thanks!

**Comment by sohaibnd** [comment]
Hi @etiennemlb, thanks for you patience.

Here is a link to the documentation for [rocprofv1](https://rocm.docs.amd.com/projects/rocprofiler/en/latest/how-to/using-rocprof.html). However, note that fbar is a **deprecated** metric from rocprofv1.

Moreover, rocprofv1 is no longer under development and there is a new **rocprofv3** released in ROCm 6.2 as a beta, which is built on top of the new [rocprofiler-sdk](https://github.com/ROCm/rocprofiler-sdk). I strongly suggest using rocprofv3 since it is very close to having feature parity, has a lower overhead than v1 and v2, and is significantly better tested. 

Here is a [link](https://rocm.docs.amd.com/projects/rocprofiler-sdk/en/latest/index.html) to the documentation for rocprofv3 (See the "Using rocprofv3" section). You can also refer to this [link](https://rocm.docs.amd.com/en/latest/conceptual/gpu-arch/mi300-mi200-performance-counters.html) for information on relevant performance counters and metrics or try "rocprofv3 --list-metrics" for a list of basic HW counters on your system.

Please let me know if need assistance with anything else!

**Comment by etiennemlb** [comment]
Im taking a look at rocprofv3, and already I like it for a simple reason.. it seems to support this syntax: `rocprofv3 <tracing_option> -- <app_relative_path>`. So finally, we can split options given to rocprof from options given to the software under profiling.

**Comment by sohaibnd** [comment]
Great! And if you encounter any issues with rocprofv3, you can create another ticket under the [rocprofiler-sdk](https://github.com/ROCm/rocprofiler-sdk) repository.
